/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.redhat.todo.api;

import com.redhat.todo.model.UsageAgreement;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-01-24T17:30:20.735351-05:00[America/New_York]")
@Validated
@Api(value = "usageagreement", description = "the usageagreement API")
public interface UsageagreementApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /usageagreement
     * The latest usage agreement
     *
     * @return The content of the usage agreement. (status code 200)
     */
    @ApiOperation(value = "", nickname = "getUsageAgreement", notes = "The latest usage agreement", response = UsageAgreement.class, tags={ "usageAgreement", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The content of the usage agreement.", response = UsageAgreement.class) })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/usageagreement",
        produces = { "application/json" }
    )
    default ResponseEntity<UsageAgreement> getUsageAgreement() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"end_date\" : \"2000-01-23\", \"text\" : \"text\", \"version\" : 0.8008282, \"start_date\" : \"2000-01-23\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
